# Generated by Django 5.2.3 on 2025-06-19 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_reviewprofessor_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(related_name='professor', to='professor.course'),
        ),
        migrations.AddField(
            model_name='reviewprofessor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professor.course'),
        ),
    ]
