# Generated by Django 5.2.3 on 2025-06-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
